# Generated by Django 4.0.5 on 2022-10-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_statementpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
