# Generated by Django 4.0.5 on 2022-10-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_statementpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatementPage',
        ),
    ]
